// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARGKQcQnelwKhKNCUas1wgelWcvw8tqE',
    appId: '1:291270115281:web:a62666cb4b5d54cbc66af0',
    messagingSenderId: '291270115281',
    projectId: 'fir-practice-c8bff',
    authDomain: 'fir-practice-c8bff.firebaseapp.com',
    databaseURL: 'https://fir-practice-c8bff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c8bff.appspot.com',
    measurementId: 'G-8L3J6WL8DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVaAaFtsvY8_lE1A-waasXWr-jY8JN0-Q',
    appId: '1:291270115281:android:c558de01314d7642c66af0',
    messagingSenderId: '291270115281',
    projectId: 'fir-practice-c8bff',
    databaseURL: 'https://fir-practice-c8bff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c8bff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA669OUqAV72OomqxGw8MVBrGqQYhNt1gg',
    appId: '1:291270115281:ios:31913352e3805282c66af0',
    messagingSenderId: '291270115281',
    projectId: 'fir-practice-c8bff',
    databaseURL: 'https://fir-practice-c8bff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c8bff.appspot.com',
    iosBundleId: 'com.example.firebasepractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA669OUqAV72OomqxGw8MVBrGqQYhNt1gg',
    appId: '1:291270115281:ios:31913352e3805282c66af0',
    messagingSenderId: '291270115281',
    projectId: 'fir-practice-c8bff',
    databaseURL: 'https://fir-practice-c8bff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c8bff.appspot.com',
    iosBundleId: 'com.example.firebasepractice',
  );
}
